import { 
  Code, 
  Shield, 
  Palette, 
  Network, 
  Bot, 
  Brain,
  BookOpen,
  Database,
  Globe,
  Layers,
  Monitor,
  Smartphone,
  Server,
  Lock,
  Cloud,
  Cpu,
  FileCode,
  Workflow
} from 'lucide-react';

export const moduleIconOptions = [
  { value: 'Code', label: 'Code', icon: Code },
  { value: 'BookOpen', label: 'Book Open', icon: BookOpen },
  { value: 'Database', label: 'Database', icon: Database },
  { value: 'Globe', label: 'Globe', icon: Globe },
  { value: 'Layers', label: 'Layers', icon: Layers },
  { value: 'Monitor', label: 'Monitor', icon: Monitor },
  { value: 'Smartphone', label: 'Smartphone', icon: Smartphone },
  { value: 'Server', label: 'Server', icon: Server },
  { value: 'Lock', label: 'Lock', icon: Lock },
  { value: 'Cloud', label: 'Cloud', icon: Cloud },
  { value: 'Cpu', label: 'CPU', icon: Cpu },
  { value: 'FileCode', label: 'File Code', icon: FileCode },
  { value: 'Workflow', label: 'Workflow', icon: Workflow },
  { value: 'Shield', label: 'Shield', icon: Shield },
  { value: 'Palette', label: 'Palette', icon: Palette },
  { value: 'Network', label: 'Network', icon: Network },
  { value: 'Bot', label: 'Bot', icon: Bot },
  { value: 'Brain', label: 'Brain', icon: Brain },
];