// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiiholvhyjxlutzuebpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpaWhvbHZoeWp4bHV0enVlYnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjMzODAsImV4cCI6MjA2NTk5OTM4MH0.ez0Bj9B3COmaX1BbL_5uBUL3O3CHv79OkUtjDY8yqYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});