// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrroidtrmntehxotrpua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycm9pZHRybW50ZWh4b3RycHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTE5MDgsImV4cCI6MjA2MzMyNzkwOH0.fgsTOwR4gptNZZ8laeC8ZA89yBAzpkIZbF3EwsJIyPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);